### ISSUE TITLE
TestDateTime.test_date_this_period fails on 32bit

### ISSUE THREAD

**Issue by scarabeusiv** [joke2k/faker#921] opened 2019-03-11 12:08 UTC
```
[  180s] ______________________ TestDateTime.test_date_this_period ______________________
[  180s] 
[  180s] self = <tests.providers.test_date_time.TestDateTime testMethod=test_date_this_period>
[  180s] 
[  180s]     def test_date_this_period(self):
[  180s]         # test century
[  180s]         assert self.factory.date_this_century(after_today=False) <= date.today()
[  180s] >       assert self.factory.date_this_century(before_today=False, after_today=True) >= date.today()
[  180s] 
[  180s] tests/providers/test_date_time.py:319: 
[  180s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[  180s] faker/providers/date_time/__init__.py:1818: in date_this_century
[  180s]     return self.date_between_dates(today, next_century_start)
[  180s] faker/providers/date_time/__init__.py:1680: in date_between_dates
[  180s]     return self.date_time_between_dates(date_start, date_end).date()
[  180s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[  180s] 
[  180s] self = <faker.providers.date_time.en_US.Provider object at 0xb5b7a80c>
[  180s] datetime_start = date(2019, 3, 11), datetime_end = date(2100, 1, 1)
[  180s] tzinfo = None
[  180s] 
[  180s]     def date_time_between_dates(
[  180s]             self,
[  180s]             datetime_start=None,
[  180s]             datetime_end=None,
[  180s]             tzinfo=None):
[  180s]         """
[  180s]         Takes two DateTime objects and returns a random datetime between the two
[  180s]         given datetimes.
[  180s]         Accepts DateTime objects.
[  180s]     
[  180s]         :param datetime_start: DateTime
[  180s]         :param datetime_end: DateTime
[  180s]         :param tzinfo: timezone, instance of datetime.tzinfo subclass
[  180s]         :example DateTime('1999-02-02 11:42:52')
[  180s]         :return DateTime
[  180s]         """
[  180s]         if datetime_start is None:
[  180s]             datetime_start = datetime.now(tzinfo)
[  180s]     
[  180s]         if datetime_end is None:
[  180s]             datetime_end = datetime.now(tzinfo)
[  180s]     
[  180s]         timestamp = self.generator.random.randint(
[  180s]             datetime_to_timestamp(datetime_start),
[  180s]             datetime_to_timestamp(datetime_end),
[  180s]         )
[  180s]         if tzinfo is None:
[  180s] >           pick = datetime.fromtimestamp(timestamp, tzlocal())
[  180s] E           ValueError: timestamp out of range for platform time_t
```

As 32bit counter expires within this century we overflow the timer storage there. As such tests using this should skip there, or alternatively different means to store these values should be used:

Following tests all fail with the same:
* TestDateTime.test_date_time_this_period_with_tzinfo
* TestDateTime.test_date_time_this_period
* TestDateTime.test_date_this_period

**Comment by fcurella** [comment] 2019-03-11 15:12
Duplicate of #912

**Closed by fcurella** 2019-03-11 15:12 UTC
