### ISSUE TITLE
text-unidecode is released under the Artistic license

### ISSUE THREAD

**Issue by moggers87** [joke2k/faker#727] opened 2018-03-14 18:02 UTC
`text-unidecode` is released under the Artistic license v1.0, which is considered non-free by the FSF (and therefore not compatible with the GPL). I believe this clause is also of concern to commercial users of faker too:

> 5. You may charge a reasonable copying fee for any distribution of this Package. You may charge any fee you choose for support of this Package. You may not charge a fee for this Package itself. However, you may distribute this Package in aggregate with other (possibly commercial) programs as part of a larger (possibly commercial) software distribution provided that you do not advertise this Package as a product of your own.

Not being able to charge a fee for the software is problematic for those of us who are contractors, for example.

I realise there aren't really any good alternatives (`unidecode` is GPL licensed as pointed out in #628 , `isounidecode` doesn't support Python 3), so would a patch making `text-unidecode` an optional dependency be acceptable?

**Comment by fcurella** [comment] 2018-03-14 19:57
According to https://en.wikipedia.org/wiki/Artistic_License, the Artistic license allows linking from code with a different license.

I think 'this Package' in 'You may not charge a fee for this Package' refers to `text-unidecode`, not to `Faker`.

**Comment by moggers87** [comment] 2018-03-14 20:56
> According to https://en.wikipedia.org/wiki/Artistic_License, the Artistic license allows linking from code with a different license.

That's true of the any FOSS license, surely? The problem of license compatibility comes from two licenses having conflicting terms. E.g. you can't use Apache licensed code with a GPLv2 project due to Apache's patent clause conflicting with the GPLv2's "no additional restrictions" clause.

With regard to the Artistic license v1.0, I think it's clause 5 (the restrictions on commercial use) that make it non-free in the eyes of the FSF.

> I think 'this Package' in 'You may not charge a fee for this Package' refers to text-unidecode, not to Faker.

Yes, that's how I understood it too. But I can't distribute Faker without text-unidecode.

**Comment by moggers87** [comment] 2018-03-14 20:57
Also, it appears I was wrong about `isounidecode` - it does support Python 3, it just doesn't advertise it.

**Comment by fcurella** [comment] 2018-03-14 21:00
@moggers87 Can you send a PR taht replaces `text-unidecode` with `isounidecode`? I'm ok with replacing it ff the build passes on all configurations

**Comment by moggers87** [comment] 2019-03-04 23:11
Did something change with the license of text-unidecode?

**Comment by fcurella** [comment] 2019-03-05 00:10
Sorry, I closed it by accident

**Comment by dmsimard** [comment] 2019-07-10 16:19
@fcurella I came across this issue when packaging dependencies for inclusion in the Fedora distribution and wanted to mention that it is still problematic.

The "Artistic 1.0" license is explicitely listed in incompatible licenses here: https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing#Bad_Licenses

> These are software licenses which are NOT OKAY for Fedora. Nothing in Fedora is permitted to use these licenses. They're either non-free or deprecated.

It is documented on [gnu.org](http://www.gnu.org/licenses/license-list.html#ArtisticLicense) as:

> Artistic License 1.0 (#ArtisticLicense)
> We cannot say that this is a free software license because it is too vague; some passages are too clever for their own good, and their meaning is not clear. We urge you to avoid using it, except as part of the disjunctive license of Perl.

**Comment by fcurella** [comment] 2019-07-10 16:24
@dmsimard I 100% agree with you.

The problem is that we don't have any decent alternative. If you can think of any solution, please let us know (and possibly send a PR ;)

**Comment by dmsimard** [comment] 2019-07-10 16:54
@fcurella I am actually not familiar with faker but it looks like the only place where text-unidecode is used is here: https://github.com/joke2k/faker/blob/c412d56e6a8f3681cfa1b75ef6ed47bc9798825d/faker/providers/internet/__init__.py#L126

Surely there could be an alternative implementation ?
Unicode became standard in [python3](https://docs.python.org/3/howto/unicode.html) and python2 is end-of-life in [5 months](https://pythonclock.org/).

**Comment by fcurella** [comment] 2019-07-10 17:02
@dmsimard 

We use `text-unidecode` for transliteration, ie: taking Unicode data and trying to represent it in US-ASCII characters. For example `u'какой` -> `u'kakoi-to tekst'`

> Surely there could be an alternative implementation ?

There is one, but it's not actively maintained. See https://github.com/joke2k/faker/pull/728

> Unicode became standard in python3 and python2 is end-of-life in 5 months.

In 5 months, we can finally drop Python2. But we'll still need a library for transliteration.

**Comment by jorti** [comment] 2019-09-05 08:05
text-unidecode has switched its license in version 1.3 to GPL+ or Artistic.

**Comment by moggers87** [comment] 2019-09-05 13:29
Good to know, running tests against 1.3 and will submit a PR shortly

**Closed** 2019-09-05 14:23 UTC

**Comment by jimleroyer** [comment] 2022-01-28 19:36
It does not seem [that text-unidecode is using the version 2](https://github.com/kmike/text-unidecode/issues/9) of the artistic license which makes it compatible with other licenses such as MIT, but rather switched to the initial non-compat version 1. I wanted for the [open source GCNotify project](https://github.com/cds-snc/notification-api) to use faker but from what I learned, artistic v1 will not suit MIT, which faker also depend upon. 

I am not well versed with the subtleties of licensing so feel free to enlighten me, but I wonder how can faker even be able to depend on text-unidecode if the latter does not use artistic v2? 

Thanks for your awesome library btw, I just wish I could use it.

**Comment by fcurella** [comment] 2022-01-31 23:25
@jimleroyer I've replaced `text-unidecode` with my own implementation and removed the dependency.

**Comment by jimleroyer** [comment] 2022-02-01 13:44
Honestly impressed, what an amazing support. If I can help in the future with an issue, I will take a deeper look.
