### ISSUE TITLE
postal zip code not correctly related to address

### ISSUE THREAD

**Issue by FrancYescO** [joke2k/faker#1585] opened 2022-01-02 23:42 UTC
When generating an address, zip codes seems are totally unrelated to the generated address/country

i'm just taking it_IT as example (maybe a difficult one...), ZIP = CAP

The zip code in the most case is 1:1 with a city, but there are some cases of 1:n (i.e. big cities have multiple zip, based on the specific street) and some rare case of n:1 (same zip for multiple cities)
here is a good feed for italy
https://github.com/matteocontrini/comuni-json/blob/master/comuni.json

this feed can also help to have a good match between city and province (actually also unrelated that will cause to have an invalid address)

i know can be a little challenging and overkill to have an address related to the street, but at least attach it the the related city, or at least to country should be a must have

**Comment by fcurella** [comment] 2022-01-03 14:55
It's always a trade-off between how realistic we want the data to be, the complexity of the code, and the ease of maintenance.

I'm also wary of using the specific feed you mention, because their license is a little murky. I don't blame the author – they did the best under the circumstances. My worry is that distro packagers will have an issue with it.

If you have time to work an Pull Request that uses a data source with a clear license (even if it's a little incomplete or outdated), I'll be happy to review it :)

**Comment by FrancYescO** [comment] 2022-01-03 20:56
for the first point, i think at least when using the full address func, we should find a way to have a realistic address, as most application are checking the `ZIP - City` relation, or at lest `ZIP - Country`..

for an italy dataset i'll try to find something with a clear license... but as the source is from a gov entity i don't think using the dataset posted above can be an issue..

**Comment by fcurella** [comment] 2022-01-03 22:24
> i don't think using the dataset posted above can be an issue..

I dont _think_ so either. The problem is in that ambiguity. What I'm supposed to tell a distro maintainer raising (legitimate) questions?

I would prefer to tradeoff accuracy and completeness for a clear license, in this case. If that's possible.

**Comment by FrancYescO** [comment] 2022-01-04 10:25
For italy dataset..
https://github.com/Samurai016/Comuni-ITA
https://comuni-ita.herokuapp.com/api/comuni
https://comuni-ita.herokuapp.com/api/province
or
https://github.com/italia/anpr/blob/master/src/_static/xlsx/tab_comuni.xlsx (no way to link to a zip code)

For a more general zip-country-city relation... i think we can find various feeds around, just need to know if is in the interest of the project to embed it in this way...
https://github.com/Zeeshanahmad4/Zip-code-of-all-countries-cities-in-the-world-CSV-TXT-SQL-DATABASE
https://github.com/midwire/free_zipcode_data

**Comment by fcurella** [comment] 2022-01-04 16:52
I think it would be ok to take the `xlsx` from ANPR and convert it to CSV, and have python load that. As long as we put a comment with attribution as per [CC-BY](https://github.com/italia/anpr/blob/master/LICENSE). It won't be as complete as `matteocontrini/comuni-json/`, but I'm ok with that.

**Comment by FrancYescO** [comment] 2022-01-04 23:33
Just found another datasource, more complete (the ANPR one have all cities uppercased and no zip codes..) and that can be used for all the world: https://download.geonames.org/export/zip/

license is the same CC 4.0 ... let me know if it's okay to embed somehow this db

**Comment by fcurella** [comment] 2022-01-05 15:47
@FrancYescO geonames looks good 👍🏼

**Comment by fcurella** [comment] 2022-02-04 16:56
Closed by #1593

**Closed by fcurella** 2022-02-04 16:56 UTC
