### ISSUE TITLE
Remove randomness dependency on PYTHONHASHSEED

### ISSUE THREAD

**Issue by adamchainz** [joke2k/faker#363] opened 2016-07-12 16:32 UTC
We're using `faker` extensively in our test suite with `factory-boy` to generate dummy data. I love it! To help with repeatability in tests, I developed the pytest plugin `pytest-randomly` to allow re-using the `random` seed between test runs, so if they fail we can reuse the seed to get back the same random data from `faker` and debug the test.

Unfortunately we're moving from Python 2 to 3 and this includes activating `PYTHONHASHSEED` by default. We're currently trying to add it on Python 2 so that we're ready.

Since `PYTHONHASHSEED` means that dictionary iteration order is random, it means that anything that depends on this breaks. This is generally good as if you really depend on the iteration order, you should use a different data structure.

Unfortunately the way Faker generates _some_ random data (specifically I've found `random_element` when using a `dict`) is affected by dictionary iteration order. This means that fixing the random seed for the `random` module isn't enough, and one would need to fix `PYTHONHASHSEED` too. What a pain! It's also quite hard to do since there isn't a way inside a python process to query what the value of `PYTHONHASHSEED` is, unless it was explicitly set as an environment variable as opposed to set to `'random'`.

I think it would be better if Faker just didn't depend on dictionary iteration order, so its random data is also repeatable. This should be possible in most cases by swapping `dict` for `OrderedDict`.

**Comment by fcurella** [comment] 2016-07-12 16:40
Thank for the report @adamchainz

I think `random_element` method is good the way it currently is.

The issue is with specific providers that declare weighted elements as `dict`s instead of `OrderedDict`. We need to audit and fix them.

Additionally, I think this is something that should be mentioned in docs, including examples and docstrings.

**Comment by adamchainz** [comment] 2016-07-12 16:46
Just realized `OrderedDict` is 2.7+ but Faker still supports 2.6. Lists of tuples is probably the way to go here then? Unless you want to add a backport dependency for `OrderedDict` from somewhere.

**Comment by kevin-brown** [comment] 2016-07-12 17:33
You could always introduce a Python 2.6 dependency on the `ordereddict` package and fall back to it.

http://stackoverflow.com/q/1617078/359284

**Comment by adamchainz** [comment] 2016-07-13 09:12
Thanks @kevin-brown , probably the best solution

**Comment by fcurella** [comment] 2016-07-13 14:21
FWIW, dropping support for python 2.6 would also allows us to stop including importing `importlib` in [our requirements](https://github.com/joke2k/faker/blob/master/setup.py#L62).

**Comment by jeffwidman** [comment] 2016-08-04 13:45
+1 for dropping 2.6. Anyone who wants to stay on 2.6 at this point is most likely just maintaining an app and not writing something new, so they can just use an old version of `faker`.

**Comment by fcurella** [comment] 2016-09-09 22:34
I think this might have been fixed in #384. Leaving this open for now in case I've missined something. I will close next week is there's nothing wrong

**Comment by adamchainz** [comment] 2016-09-11 20:30
Awesome, thanks for the tedious PR. I started on one but there were so many dicts to convert, then I was away for a bit. One thing my local changes make is to ban `dict`s in `random_element` and only allow `OrderedDict`s, see #385.

**Closed** 2019-02-27 23:32 UTC
Labels: bug

**Comment by timschwab** [comment] 2022-01-19 19:49
Today I was informed by the error message that the `random_element` provider does not accept a dict as an argument but instead requires an OrderedDict. That message sent me here, which is why I'm deciding to resurrect a long dead issue to ask if this constraint is still needed. As of Python 3.7, iteration over a dict is guaranteed to be in insertion order. This makes the two objects [nearly identical](https://stackoverflow.com/a/57072435/1455074). I would be happy to submit a PR to remove this restriction if you guys agree.

**Comment by fcurella** [comment] 2022-01-19 22:30
@timschwab Thanks for pointing that out. Being able to use `dict` instead of `OrderedDict` sure sounds nice! Feel free to submit your PR!

**Comment by fdemmer** [comment] 2023-08-28 17:12
@timschwab did you ever get around to writing that change?

**Comment by timschwab** [comment] 2023-08-28 23:29
Hey @fdemmer unfortunately no, I got pulled away from the project.
