### ISSUE TITLE
Base provider methods are documented with the address provider.

### ISSUE THREAD

**Issue by 153957** [joke2k/faker#642] opened 2017-11-02 16:05 UTC
In the docs the [BaseProvider methods](https://github.com/joke2k/faker/blob/master/faker/providers/__init__.py) are grouped with the [address provider](https://github.com/joke2k/faker/blob/master/faker/providers/address/__init__.py). Here is the documentation: http://faker.readthedocs.io/en/master/providers/faker.providers.address.html

I would expect those to be in their own category, and they have nothing to do with addresses.

**Comment by malefice** [comment] 2019-11-07 12:05
Duplicate of #832

**Closed** 2019-11-07 16:00 UTC
Labels: bug, help wanted
